### ISSUE TITLE
Error : Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by UnrilWever** [Tal500/sveltekit-legacy-demo#4]
I change the @sveltejs/kit dependency to the one which publish from this repository [https://github.com/Tal500/kit](url)
But I got an error:
![image](https://user-images.githubusercontent.com/75024633/227828545-4b848fe9-4da2-48e7-b8eb-702f2e41e8e0.png)

So I wonder is this an unsolved problem?

**Comment by Tal500** [comment]
> I change the @sveltejs/kit dependency to the one which publish from this repository [https://github.com/Tal500/kit](url) But I got an error: ![image](https://user-images.githubusercontent.com/75024633/227828545-4b848fe9-4da2-48e7-b8eb-702f2e41e8e0.png)
> 
> So I wonder is this an unsolved problem?

Hi! Can you share your demo, or at least all of the following: "package.json", "vite.config.js"(or .ts) and "svelte.config.js"?

**Comment by UnrilWever** [comment]
I create a demo [https://github.com/UnrilWever/sveltekit-legacy-demo](https://github.com/UnrilWever/sveltekit-legacy-demo)
I just clone this repo [https://github.com/UnrilWever/sveltekit-legacy-demo](https://github.com/UnrilWever/sveltekit-legacy-demo)
and change the 
"@sveltejs/kit": "npm:@unrilwever/kit@1.12.0-legacy-build" in package.json （publish from [https://github.com/sveltejs/kit](https://github.com/sveltejs/kit) ）
to
"@sveltejs/kit": "npm:@tal500/kit@1.8.3-legacy-builds-12"

and npm run build

then the error happen
you can try it and see if the same error happens

**Comment by Tal500** [comment]
> I create a demo https://github.com/UnrilWever/sveltekit-legacy-demo I just clone this repo https://github.com/UnrilWever/sveltekit-legacy-demo and change the "@sveltejs/kit": "npm:@unrilwever/[kit@1.12.0-legacy-build](mailto:kit@1.12.0-legacy-build)" in package.json （publish from https://github.com/sveltejs/kit ） to "@sveltejs/kit": "npm:@tal500/kit@1.8.3-legacy-builds-12"
> 
> and npm run build
> 
> then the error happen you can try it and see if the same error happens

Per each of the following, after "pnpm install && pnpm build":

* "@sveltejs/kit": "npm:@unrilwever/kit@1.12.0-legacy-build" - doesn't work
* "@sveltejs/kit": "npm:@tal500/kit@1.8.3-legacy-builds-12" - works well
* Installation from the local directory in my machine pointing to "kit/packages/kit" of version https://github.com/Tal500/kit/commit/bf9e41a90d2325b8eb0ec9c852b00a3972fe4449 - works well

Don't know what you did on package "npm:@unrilwever/kit@1.12.0-legacy-build", but notice you need PR https://github.com/sveltejs/kit/pull/6265 to work.

**Comment by Tal500** [comment]
Closing it because on inactivity, welcome to ask more or to open a new issue if not answered.
